modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="paranoiamod"
version="1.0.0"
displayName="Paranoia"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jean, MCreator"

[[dependencies.paranoiamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




